// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redfinlib.proto

package redfinlib

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Stats_SaleState int32

const (
	Stats_UNKNONW  Stats_SaleState = 0
	Stats_FOR_SALE Stats_SaleState = 1
	Stats_PENDING  Stats_SaleState = 2
	Stats_SOLD     Stats_SaleState = 3
)

var Stats_SaleState_name = map[int32]string{
	0: "UNKNONW",
	1: "FOR_SALE",
	2: "PENDING",
	3: "SOLD",
}

var Stats_SaleState_value = map[string]int32{
	"UNKNONW":  0,
	"FOR_SALE": 1,
	"PENDING":  2,
	"SOLD":     3,
}

func (x Stats_SaleState) String() string {
	return proto.EnumName(Stats_SaleState_name, int32(x))
}

func (Stats_SaleState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ddaac600666cb139, []int{0, 0}
}

type Stats struct {
	CurrentPrice         int32           `protobuf:"varint,1,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	CurrentEstimate      int32           `protobuf:"varint,2,opt,name=current_estimate,json=currentEstimate,proto3" json:"current_estimate,omitempty"`
	State                Stats_SaleState `protobuf:"varint,3,opt,name=state,proto3,enum=redfinlib.Stats_SaleState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddaac600666cb139, []int{0}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetCurrentPrice() int32 {
	if m != nil {
		return m.CurrentPrice
	}
	return 0
}

func (m *Stats) GetCurrentEstimate() int32 {
	if m != nil {
		return m.CurrentEstimate
	}
	return 0
}

func (m *Stats) GetState() Stats_SaleState {
	if m != nil {
		return m.State
	}
	return Stats_UNKNONW
}

func init() {
	proto.RegisterEnum("redfinlib.Stats_SaleState", Stats_SaleState_name, Stats_SaleState_value)
	proto.RegisterType((*Stats)(nil), "redfinlib.Stats")
}

func init() { proto.RegisterFile("redfinlib.proto", fileDescriptor_ddaac600666cb139) }

var fileDescriptor_ddaac600666cb139 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0x4d, 0x49,
	0xcb, 0xcc, 0xcb, 0xc9, 0x4c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x9d, 0x60, 0xe4, 0x62, 0x0d, 0x2e, 0x49, 0x2c, 0x29, 0x16, 0x52, 0xe6, 0xe2, 0x4d, 0x2e, 0x2d,
	0x2a, 0x4a, 0xcd, 0x2b, 0x89, 0x2f, 0x28, 0xca, 0x4c, 0x4e, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0d, 0xe2, 0x81, 0x0a, 0x06, 0x80, 0xc4, 0x84, 0x34, 0xb9, 0x04, 0x60, 0x8a, 0x52, 0x8b, 0x4b,
	0x32, 0x73, 0x13, 0x4b, 0x52, 0x25, 0x98, 0xc0, 0xea, 0xf8, 0xa1, 0xe2, 0xae, 0x50, 0x61, 0x21,
	0x03, 0x2e, 0xd6, 0xe2, 0x12, 0x90, 0x3c, 0xb3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x94, 0x1e, 0xc2,
	0x15, 0x60, 0x0b, 0xf5, 0x82, 0x13, 0x73, 0x52, 0x41, 0xac, 0xd4, 0x20, 0x88, 0x42, 0x25, 0x5b,
	0x2e, 0x4e, 0xb8, 0x98, 0x10, 0x37, 0x17, 0x7b, 0xa8, 0x9f, 0xb7, 0x9f, 0xbf, 0x5f, 0xb8, 0x00,
	0x83, 0x10, 0x0f, 0x17, 0x87, 0x9b, 0x7f, 0x50, 0x7c, 0xb0, 0xa3, 0x8f, 0xab, 0x00, 0x23, 0x48,
	0x2a, 0xc0, 0xd5, 0xcf, 0xc5, 0xd3, 0xcf, 0x5d, 0x80, 0x49, 0x88, 0x83, 0x8b, 0x25, 0xd8, 0xdf,
	0xc7, 0x45, 0x80, 0x39, 0x89, 0x0d, 0xec, 0x39, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb,
	0xcb, 0xb7, 0x9d, 0xef, 0x00, 0x00, 0x00,
}
